### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by rubik** [JohnLato/posix-paths#16]
Would it be possible to update `criterion` to `1.1.0.0` and `filepath` to `1.4.0.0`?
See https://github.com/fpco/stackage/issues/1215

Thanks!

**Comment by hasufell** [comment]
https://github.com/JohnLato/posix-paths/pull/19/commits/221025bb15f4f80311c8d920222a8a9d8724e303

**Comment by rubik** [comment]
Thanks @hasufell!

**Comment by nh2** [comment]
Looks like this is done.
